/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#351000",
        "outline": "#737783",
        "surface-container-highest": "#e0e3e5",
        "on-secondary": "#ffffff",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#264c80",
        "primary": "#043568",
        "surface-tint": "#3a5f94",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed-dim": "#ffb694",
        "tertiary-container": "#833301",
        "secondary-container": "#cbe7f5",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "inverse-primary": "#a7c8ff",
        "on-secondary-fixed": "#021f29",
        "secondary-fixed": "#cbe7f5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffa77e",
        "on-primary-fixed-variant": "#1f477b",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#9abef9",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#304a55",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface": "#f7f9fb",
        "on-secondary-container": "#4e6874",
        "primary-fixed-dim": "#a7c8ff",
        "on-primary-fixed": "#001b3c",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c2c6d3",
        "secondary-fixed-dim": "#afcbd8",
        "primary-fixed": "#d5e3ff",
        "secondary": "#48626e",
        "surface-bright": "#f7f9fb",
        "on-background": "#191c1e",
        "error": "#ba1a1a",
        "surface-container": "#eceef0",
        "on-surface-variant": "#424751",
        "tertiary": "#5f2200",
        "background": "#f7f9fb"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
